[project]
name = "technicaltest"
version = "0.1.0"
description = "Recyclever Technical Test"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.27.0",
    "pydantic>=2.0.0",
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0"
]

[tool.poetry]
package-mode = false
